### ISSUE TITLE
Integrate into the dropdown panel of wifi setting. [Enhancement]

### ISSUE THREAD

**Issue by jccode** [tomflannaghan/proxy-switcher#2]
Thanks for the great jobs! 
Is it possible to integrate this switcher into the wifi-setting panel? I mean the below panel:

![12](https://cloud.githubusercontent.com/assets/2819095/5982982/c9e46446-a903-11e4-844b-4de3618fcf07.png)

That would be perfect. Thanks.

**Comment by Skatox** [comment]
I'm agree to this idea. It's better to have this on that panel.

**Comment by tomflannaghan** [comment]
I agree that would be cool! Originally, I put it on the top bar because I modelled my code on another extension that has a similar popup, but your suggestion makes a lot of sense. If I have time I'll try to move it, but I won't promise anything!

**Comment by tomflannaghan** [comment]
Turns out this was simpler than I expected... how does this look:

![image](https://cloud.githubusercontent.com/assets/1344509/7241061/27257190-e784-11e4-8058-d61a73649e78.png)

I've pushed the change to the github repository (but not to the gnome extensions website yet). If you could test it works in 3.16 that would be awesome.

**Comment by Skatox** [comment]
I couldn't compile it, it says that **locale** file is missing. What's that file?

**Comment by tomflannaghan** [comment]
Apologies for that. The makefile was missing the step to create it, and when I tested, I had a dirty copy. I've pushed a fix.

**Comment by Skatox** [comment]
I've install it and looks good! But I cannot see what's my current selection, I don't have problems with this but some users might.

Also, I had a problem when compiliing under Archlinux because python's binary is *python2*, I'll check if I can do something about it.
![proxy-switcher](https://cloud.githubusercontent.com/assets/177008/7260985/0bc30e80-e838-11e4-878f-485803b26bdb.png)

**Comment by Skatox** [comment]
My mistake, I can see the select option at the menu. This issue can be closed, I tested it under Gnome 3.16 and works.

**Comment by tomflannaghan** [comment]
Thanks a lot for testing and the feedback. I've also just pushed a change for the make_locale.py script that makes it compatible with both python 2 and python 3 so hopefully you'll be able to build on archlinux.

**Comment by jccode** [comment]
Awesome! Thumb up :+1:

**Comment by Skatox** [comment]
Thanks for the changes and the plugin, it makes my life easier, since I've to switch to proxy and no proxy multiple times at day.
